---
- name: Deploy Flask App Docker Container
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Pull Flask app Docker image
      community.docker.docker_image:
        name: lakshithaiam/my-flask-app
        source: pull

    - name: Run Flask app container
      community.docker.docker_container:
        name: flask_app
        image: lakshithaiam/my-flask-app
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
