---
- name: Test Python Interpreter
  hosts: 
    - instance_name_my_instance_1
    - instance_name_my_instance_2
    
  tasks:
    - name: Print Python Version
      command: python3 --version
      register: python_version
    - name: Show Python Version
      debug:
        msg: Python version on host is {{ python_version.stdout }}

